<a href="https://colab.research.google.com/github/SohanKumar56/23102A0056_RPROGRAMMING/blob/main/Week4_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Creating a Matrix

In [1]:
x <- matrix(nrow = 4, ncol = 3, data = c(1:12))
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

### 2. Renaming the Names of Rows and Columns

In [2]:
rownames(x) <- c("r1", "r2", "r3", "r4")
colnames(x) <- c("c1", "c2", "c3")
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

### 3. Assigning a Specified Number to All Matrix Elements

In [3]:
x <- matrix(nrow = 4, ncol = 2, data = 2)
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

### 4. Construction of a Diagonal / Identity Matrix

In [4]:
d <- diag(1, nrow = 3, ncol = 3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

### 5. Diagonal Matrix with All Diagonal Elements Equal to 5

In [5]:
d <- diag(5, nrow = 3, ncol = 3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

### 6. Transpose of a Matrix

In [6]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)
x

xt <- t(x)
xt

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

### 7. Finding Row and Column Sums

In [7]:
x <- matrix(nrow = 4, ncol = 2, data = c(1,2,3,4,5,6,7,8))
x

rowSums(x)
colSums(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1]  6  8 10 12

[1] 10 26

### 8. Finding Row and Column Means

In [8]:
x <- matrix(nrow = 4, ncol = 2, data = c(1,2,3,4,5,6,7,8))
x

rowMeans(x)
colMeans(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] 3 4 5 6

[1] 2.5 6.5

### 9. Creating a Matrix by Row

In [9]:
x <- matrix(nrow = 5, ncol = 3, byrow = TRUE, data = 1:15)
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

### 10. Accessing a Row

In [10]:
x[3,]

[1] 7 8 9

### 11. Accessing a Column

In [11]:
x[,2]

[1]  2  5  8 11 14

### 12. Accessing a Submatrix

In [12]:
x[4:5, 2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

### 13. Accessing Selected Rows and Columns

In [15]:
x[c(1,4), c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

### 14. Selecting a Column from a Matrix

In [16]:
x[,2]

[1]  2  5  8 11 14

### 15. Addition of a Matrix with a Constant

In [17]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)
x
x + 5

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

### 16. Subtraction of a Matrix with a Constant

In [18]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)
x
x - 5

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

### 17. Multiplication of a Matrix with a Constant

In [19]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)
x
5 * x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

### 18. Division of a Matrix with a Constant

In [20]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)
x
x / 2

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

### 19. Addition and Subtraction of Matrices

In [21]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)
y <- matrix(nrow = 4, ncol = 2, data = 11:18, byrow = TRUE)

x
y

x + y
x - y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

### 20. Scalar Multiplication and Matrix Expressions

In [22]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)
x

4 * x

x + 4 * x

4 * x - x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

### 21. Matrix Multiplication using `%*%`

In [24]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)
y <- matrix(nrow = 2, ncol = 4, data = 11:18, byrow = TRUE)

x
y

x %*% y
y %*% x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 11   12   13   14
[2,] 15   16   17   18

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

     [,1] [,2]
[1,] 210  260
[2,] 274  340

### 22. Multiplication of X' and X

In [25]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)
x

t(x)

t(x) %*% x

x %*% t(x)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

### 23. Cross Product using `crossprod()`

In [26]:
x <- matrix(nrow = 4, ncol = 2, data = 1:8, byrow = TRUE)
x

crossprod(x)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  84  100
[2,] 100  120

### 24. Concatenating Matrices Row-wise using `rbind()`

In [27]:
x <- matrix(nrow = 3, ncol = 2, data = 1:6, byrow = TRUE)
y <- matrix(nrow = 3, ncol = 2, data = 11:16, byrow = TRUE)

x
y

rbind(x, y)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

### 25. Concatenating Matrices Column-wise using `cbind()`

In [28]:
x <- matrix(nrow = 3, ncol = 2, data = 1:6, byrow = TRUE)
y <- matrix(nrow = 3, ncol = 2, data = 11:16, byrow = TRUE)

x
y

cbind(x, y)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

### 26. Finding the Inverse of a Matrix using `solve()`

In [29]:
y <- matrix(
  nrow = 2,
  ncol = 2,
  byrow = TRUE,
  data = c(84, 100, 100, 120)
)

y
solve(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

### 27. Finding Eigenvalues and Eigenvectors using `eigen()`

In [30]:
y <- matrix(
  nrow = 2,
  ncol = 2,
  byrow = TRUE,
  data = c(84, 100, 100, 120)
)

y
eigen(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

### 28. Logical and Comparison Operators

Common operators used in R:

- `>` Greater than
- `>=` Greater than or equal to
- `<` Less than
- `<=` Less than or equal to
- `==` Exactly equal to
- `!=` Not equal to
- `!` Logical NOT
- `&`, `&&` Logical AND
- `|`, `||` Logical OR
- `xor(x, y)` Exclusive OR
- `isTRUE(x)` Tests whether `x` is TRUE
- `isFALSE(x)` Tests whether `x` is FALSE

### 29. Example of `|` and `||`

In [31]:
x <- 8
(x < 10) || (x < 2)

x <- 18
(x < 10) || (x < 2)

[1] TRUE

[1] FALSE

### 30. Element-wise `|` versus `||`

In [32]:
x <- c(8, 18)

(x < 10) || (x < 2)
(x < 10) | (x < 2)

ERROR: Error in (x < 10) || (x < 2): 'length = 2' in coercion to 'logical(1)'

### 31. Example of `&` and `&&`

In [33]:
x <- 5
(x < 10) && (x > 2)

x <- 15
(x < 10) && (x > 2)

[1] TRUE

[1] FALSE

### 32. Element-wise `&` versus `&&`

In [34]:
x <- c(8, 18)

(x < 10) && (x > 2)
(x < 10) & (x > 2)

ERROR: Error in (x < 10) && (x > 2): 'length = 2' in coercion to 'logical(1)'

### 33. Filtering a Vector using Logical Conditions

In [35]:
x <- 1:6 # 1,2,3,4,5,6

(x > 2) & (x < 5)

x[(x > 2) & (x < 5)]

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] 3 4

### 34. Filtering using Logical OR

In [36]:
x <- 1:6

(x > 2) | (x < 5)

x[(x > 2) | (x < 5)]

[1] TRUE TRUE TRUE TRUE TRUE TRUE

[1] 1 2 3 4 5 6

### 35. Understanding `&&` with a Vector

In [37]:
x <- 1:6

(x > 2) && (x < 5)

# Equivalent to checking only the first element
(x[1] > 2) & (x[1] < 5)

ERROR: Error in (x > 2) && (x < 5): 'length = 6' in coercion to 'logical(1)'

### 36. Relational Operators

`TRUE` and `FALSE` are logical constants in R.

Also, in logical contexts, zero is treated as FALSE and non-zero numbers are treated as TRUE.

### 37. Standard Logical Operations

In [42]:
x <- TRUE
y <- FALSE

x & y
x | y
!x

[1] FALSE

[1] TRUE

[1] FALSE

### 38. Checking Logical Results with `is.logical()`

In [43]:
x <- 5

Logical1 <- (x > 2)
Logical1
is.logical(Logical1)

Logical2 <- (x < 10)
Logical2
is.logical(Logical2)

Logical3 <- (x != 5)
Logical3
is.logical(Logical3)

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

### 39. More Logical Expressions

In [44]:
x <- 5

Logical4 <- (2 * x > 11)
Logical4
is.logical(Logical4)

Logical5 <- (3 * x < 20)
Logical5
is.logical(Logical5)

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

### 40. Basic Relational Comparisons

In [45]:
8 > 7
7 < 5
7 > 7
7 >= 7
8 < 8
8 <= 8

8 != 9
9 != 9
7 == 7
7 == 8

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

### 41. Logical NOT

In [46]:
x <- TRUE
!x

[1] FALSE

### 42. Relational Comparisons between Vectors

In [47]:
x <- c(1, 2, 3)
y <- c(4, 5, 6)

x > y
x < y
x != y
x == y

[1] FALSE FALSE FALSE

[1] TRUE TRUE TRUE

[1] TRUE TRUE TRUE

[1] FALSE FALSE FALSE

### 43. Using `isTRUE()` and `isFALSE()`

In [48]:
isTRUE(8 < 6)
isTRUE(8 > 6)

isFALSE(5 < 8)
isFALSE(5 > 8)

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE