<a href="https://colab.research.google.com/github/SohanKumar56/23102A0056_RPROGRAMMING/blob/main/Week5_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Missing Data

In [1]:
x<- NA
is.na(x)

[1] TRUE

In [2]:
x=c(11, NA, 13, NA)
is.na(x)

[1] FALSE  TRUE FALSE  TRUE

In [3]:
x=c(11, NA, 13, NA)
mean(x)

[1] NA

In [4]:
mean(x, na.rm=TRUE)

[1] 12

### Missing data:Location of missing values

In [5]:
which(is.na(x))

[1] 2 4

In [6]:
#count of NAs
sum(is.na(x))

[1] 2

In [7]:
complete.cases(x)

[1]  TRUE FALSE  TRUE FALSE

### Missing data: Finding complete data set

In [10]:
y=na.omit(x)
y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

In [12]:
attr(y,"na.action")

[1] 2 4
attr(,"class")
[1] "omit"

In [13]:
mean(x)

[1] NA

In [14]:
mean(y)

[1] 12

## Control structures in R

## Conditional Execution: if()

In [15]:
x=5
if(x>4)
{
  x*3
}

[1] 15

In [18]:
x=3
if(x>4) x*3
## conditional false so therefore no output

In [20]:
x=6
if(x>3)
{
  print("The value is more than 3")
}

[1] "The value is more than 3"

In [22]:
x=2
if(x>3)
{
  print("The value is more than 3")
}##condition failed therfore no outcome

### Conditional execution: if else()

In [28]:
x=5
if(x==3)
{
  x=x-1
}else
{
  x=2*x
}
x

[1] 10

In [29]:
x=2
if(x==2) {x=x-1} else {x=2*x}
x

[1] 1

In [31]:
x=6
if(x>3)
{
  print("The value is more than 3")
} else {" The value is not more than 3"}

[1] "The value is more than 3"

### Nested: if else if()

In [32]:
x=5
if(x==3)
{
  x=x-1
} else if(x<3){
  x=x+5
}else{x=2*x}

x

[1] 10

In [33]:
x=2
if(x==3)
{
  x=x-1
} else if(x<3){
  x=x+5
}else{x=2*x}

x

[1] 7

In [34]:
x=3
if(x==3)
{
  x=x-1
} else if(x<3){
  x=x+5
}else{x=2*x}

x

[1] 2

ifelse(test , yes, no)
if test true then yes is executed if false then no is executed

In [35]:
x= 1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [36]:
ifelse(x<6, x^2, x+1)

 [1]  1  4  9 16 25  7  8  9 10 11

In [37]:
x=c(7,9,8,4)

ifelse(x %% 2==0, "even number", "odd number")

[1] "odd number"  "odd number"  "even number" "even number"

### Switch case

In [38]:
switch(2,"apple", "banana", "orange")

[1] "banana"

In [39]:
switch(1,"apple", "banana", "orange")

[1] "apple"

In [40]:
switch("colour","colour" = "blue", "gender"= "male", "volume"= 50)

[1] "blue"

In [41]:
switch("volume","colour" = "blue", "gender"= "male", "volume"= 50)

[1] 50

In [42]:
switch(4,"apple", "banana", "orange")

In [43]:
switch("size","colour" = "blue", "gender"= "male", "volume"= 50)

##Some functions useful in conditional execution: which()

In [44]:
x= c(10, 15, 8, 14, 6, 12)
x

[1] 10 15  8 14  6 12

In [45]:
which(x==12)

[1] 6

In [46]:
which(x!=12)

[1] 1 2 3 4 5

In [47]:
which(x>10)

[1] 2 4 6

In [49]:
x=matrix(nrow=3, ncol=3, data =1:9)
x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [50]:
which.min(x)

[1] 1

In [51]:
which.max(x)

[1] 9

In [52]:
which(x %% 2==1)

[1] 1 3 5 7 9

In [54]:
which(x %% 2==1, arr.ind = TRUE)

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3