# **Strings - Display and Formatting**

The print function has a significant limitation that it prints only one
object at a time.

In [ ]:
print("The zero occurance at", 2*pi, "radians")

ERROR: Error in print.default("The zero occurance at", 2 * pi, "radians"): invalid 'quote' argument

The only way to print multiple items is to print them one at a time

In [ ]:
print("The zero occurs at");
print(2*pi);
print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

**Formatting and Display of Strings: cat function**

The cat function is an alternative to print that lets you combine
multiple items into a continuous output.

In [ ]:
print("The zero occurs at");
print("2*pi");
print("radians")

[1] "The zero occurs at"
[1] "2*pi"
[1] "radians"

In [ ]:
cat("The zero occurs at", 2*pi, "radians.", "\n")

The zero occurs at 6.283185 radians.

In [ ]:
d = date()
cat("Today's date is:", d, "\n")

Today's date is: Tue Sep 22 08:48:26 2026

In [ ]:
x = 1:10
x

cat(x, sep =" ++ ")
cat("\n")

cat(x, sep=" /")

 [1]  1  2  3  4  5  6  7  8  9 10

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10
1 /2 /3 /4 /5 /6 /7 /8 /9 /10

In [ ]:
x = 7
cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

In [ ]:
cat("The square root of", x, "is approximtely", format(sqrt(x), digits=3), "\n")

The square root of 7 is approximtely 2.65

In [ ]:
evenno = c(2,4,6,8,10)
evenno

cat("The first few even numbers are:", evenno, "....\n")

[1]  2  4  6  8 10

The first few even numbers are: 2 4 6 8 10 ....

In [ ]:
x = 1:10
x

cat(x, fill = 2, labels = paste("(", letters[1:10], "):"))

 [1]  1  2  3  4  5  6  7  8  9 10

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

**paste() function**

In [ ]:
paste(1:12)

as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [ ]:
paste("Everday", "loves", "R Programming.")
paste("Everday", "loves", "R Programming.", sep="*")
paste("Everday", "loves", "R Programming.", sep="===")

[1] "Everday loves R Programming."

[1] "Everday*loves*R Programming."

[1] "Everday===loves===R Programming."

In [ ]:
names = c("Prof. Singh", "Mr. Venkat", "Dr. Jha")
names

paste(names, "is", "a good", "person.")

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

[1] "Prof. Singh is a good person." "Mr. Venkat is a good person."
[3] "Dr. Jha is a good person."

In [ ]:
names = c("Prof. Singh", "Mr. Venkat", "Dr. Jha")
names

paste(names, "is", "a good", "person.", collapse=", and ")

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

[1] "Prof. Singh is a good person., and Mr. Venkat is a good person., and Dr. Jha is a good person."

**Operations with Strings**

In [ ]:
paste(1, " is first", 2, " is second", 3, " is third", sep = "#")
paste(1, " is first   ", 2, " is second   ", 3, " is third    ", sep = "#")

[1] "1# is first#2# is second#3# is third"

[1] "1# is first   #2# is second   #3# is third    "

In [ ]:
x = paste("Ex", 1:5, sep ="_")
x

x[1]
x[2]
x[3]
x[5]

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

[1] "Ex_1"

[1] "Ex_2"

[1] "Ex_3"

[1] "Ex_5"

In [ ]:
x = paste("Ex", 1:5, sep="_", collapse="")
x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [ ]:
x = paste("Ex", 1:5, sep="_")
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [ ]:
paste0(1:10)
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [ ]:
paste0(1:10, c("st", "nd", "rd", rep("th", 7) ))
paste(1:10, c("st", "nd", "rd", rep("th", 7) ))

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

**String Splitting**

In [ ]:
x = "The&!syntax&!of&!paste&!is!&available!
&inthe online-help"
x
strsplit(x, split="!")

[1] "The&!syntax&!of&!paste&!is!&available!\n&inthe online-help"

[[1]]
[1] "The&"                 "syntax&"              "of&"
[4] "paste&"               "is"                   "&available"
[7] "\n&inthe online-help"

In [ ]:
x = "The&!syntax&!of&!paste&!is!&available!
&inthe online-help"
x
strsplit(x, split="&!")

[1] "The&!syntax&!of&!paste&!is!&available!\n&inthe online-help"

[[1]]
[1] "The"                                "syntax"
[3] "of"                                 "paste"
[5] "is!&available!\n&inthe online-help"

In [2]:
x = "The&!syntax&!of&!paste&!is!&available!
&inthe online-help"
x

y = strsplit(x, split = "!&")
y

y[[1]][1]
y[[1]][2]
y[[1]][3]

[1] "The&!syntax&!of&!paste&!is!&available!\n&inthe online-help"

[[1]]
[1] "The&!syntax&!of&!paste&!is"     "available!\n&inthe online-help"

[1] "The&!syntax&!of&!paste&!is"

[1] "available!\n&inthe online-help"

[1] NA

In [6]:
dates = c("2020-07-24", "2021-08-25", "2022-
09-26", "2023-10-27")

datesplt = strsplit(dates, "-")
datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "\n09" "26"

[[4]]
[1] "2023" "10"   "27"

**Convert to matrix**

In [7]:
datemat = matrix(unlist(datesplt), nrow = 4,
ncol=3, byrow=TRUE)

datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 \n09 26
[4,] 2023 10   27

In [8]:
datematrix =
matrix(as.numeric(unlist(datesplt)), nrow = 4,
ncol=3, byrow=TRUE)

datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

In [9]:
strsplit("Shalabh",split="")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

**Manipulations with Strings and Alphabets**

In [11]:
x = "R course 24.09.2026"
x

y = "Number of participants: 4460"
y

nchar(x)
nchar(y)
nzchar(x)
nzchar(y)

[1] "R course 24.09.2026"

[1] "Number of participants: 4460"

[1] 19

[1] 28

[1] TRUE

[1] TRUE

In [12]:
x = c("Apple", "Banana", "Cake")
x

nzchar(x)

y = c("Apple", "", "Cake")
y

nzchar(y)

[1] "Apple"  "Banana" "Cake"

[1] TRUE TRUE TRUE

[1] "Apple" ""      "Cake"

[1]  TRUE FALSE  TRUE

In [13]:
x = c("Apple", "Banana", "Cake")
nchar(x)

y =c(2,4,6)
nchar(y)

z = c(11,222,3333)
nchar(z)

z1 = c(1.1, 2.22, 3.333)
nchar(z1)

[1] 5 6 4

[1] 1 1 1

[1] 2 3 4

[1] 3 4 5

In [16]:
x = "R course will start from 24.07.2022"
x
toupper(x)

z = "INDIAN INSTITUTE OF TECHNOLOGY"
z
tolower(z)

[1] "R course will start from 24.07.2022"

[1] "R COURSE WILL START FROM 24.07.2022"

[1] "INDIAN INSTITUTE OF TECHNOLOGY"

[1] "indian institute of technology"